print ('***************************************')
print('My Coffee, Muffin, and More Shop')
print('Number of coffees bought?')
value1=int(input())
print('Number of muffins bought?')
value2=int(input())
print('Number of scones bought?')
value3=int(input())
print('Number of teas bought?')
value4=int(input())
print('***************************************')
print('***************************************')
print('My Coffee, Muffin, and More Shop Receipt')
coffee=value1*5
print(str(value1)+ " Coffee at $5 each: $ " + str(coffee)+ ".00")
muffin=value2*4
print(str(value2)+ " Muffins at $4 each: $ " + str(muffin)+ ".00")
scone=value3*3
print(str(value3)+ " Scones at $3 each: $ " + str(scone)+ ".00")
tea=value4*2
print(str(value4)+ " Tea at $2 each: $ " + str(tea)+ ".00")
((coffee+muffin+scone+tea)*0.06)
print("6% tax: " + str((coffee+muffin+scone+tea)*0.06))
print('---------')
print("Total: " + str(((coffee+muffin+scone+tea)+((coffee+muffin+scone+tea)*0.06))))
print('***************************************')
print('Thank You For Choosing "My Coffee, Muffins, and More Shop"! We Hope To See You Again!')
